pipeline {		// requires Jenkins plugin 'PowerShell'
    agent any		// job may run on any Jenkins node
    stages {
        stage ('Cleanup') {
            steps {
                echo "Pulled from ${env.GIT_URL}, branch ${env.GIT_BRANCH}, commit {$env.GIT_COMMIT} ..."
                sh 'git clean -xdf'
                sh 'git status'
            }
        }
        stage ('Health Check') {
            steps {
		echo "Starting build #${env.BUILD_NUMBER} on ${env.NODE_NAME} node ..."
		powershell './scripts/check-health.ps1'
            }
        }
    }
}
