<#
.SYNOPSIS
        Generates a new story
.DESCRIPTION
        This PowerShell script generates a new story by rules and randomness only and writes it to the console.
.EXAMPLE
        PS> ./new-story.ps1
	The angry Ron hits the road.
	...
.LINK
        https://github.com/fleschutz/PowerShell
.NOTES
        Author: Markus Fleschutz | License: CC0
#>

function RandomSentenceBegin {
	return "Additionally","Afterward,","Again","And slowely","And suddenly","And","And underneath","As usual","Besides","But silently","But the","Except that","Furthermore,","However,","In this situation","Just then","Meanwhile","On the other hand","Since","So then","That morning","That evening","The","The next day","Then","Whereas","While" | Get-Random
}

function RandomAdverb {
	return "angry","clever","colorful","cool","funny","glad","good","happy","holy","hot","late","lazy","loud","lovely","nice","poor","rich","romantic","sad","selfish","shy","silent","slow","smart","violent" | Get-Random
}

function RandomSubject {
	return "airport","Amy","baby","Ben","Bob","brothers","car","cat","Dick","dog","earth","Eva","fox","guy","he","jet","Joe","Jon","kids","Leo","Mark","Mary","Max","man","moon","movies","parents","people","Peter","plane","Pope","Ron","Sam","she","sisters","sun","Tim","Tom","woman" | Get-Random
}

function RandomVerb {
	return "beats","broadcasts","catches","enters","goes to","hits","leaves","listens to","loves","talks to","walks to","welcomes" | Get-Random
}

function RandomObject {
	return "a ball","a house","a sheep","a student","a table","a vase","god","the church","the road","the tea","the teacher","the woods","Lisa","Mary" | Get-Random
}

function RandomSentence {
	return "$(RandomSentenceBegin) $(RandomAdverb) $(RandomSubject) $(RandomVerb) $(RandomObject)."
}

function RandomParagraph {
	return "$(RandomSentence) $(RandomSentence) $(RandomSentence) $(RandomSentence) $(RandomSentence) $(RandomSentence) $(RandomSentence) $(RandomSentence)`n"
}

function RandomChapter {
	$global:chapter_number++
	$title = "`nChapter $($global:chapter_number): $(RandomSentence)`n"
	& "$PSScriptRoot/write-typewriter.ps1" $title 20

	for ($i = 0; $i -lt 20; $i++) {
		$paragraph = $(RandomParagraph)
		& "$PSScriptRoot/write-typewriter.ps1" $paragraph 20
	}
}

""
"                           An Endless Random Story"
"                           ======================="
""
"            Solely generated by a script with rules & randomness."
""
"  Copyright © 2026 A.I. All Rights Reserved. Violators will be terminated ;-)"
""
while ($true) { RandomChapter }
