#!/bin/sh
# NOTE: to be started as superuser!
#       requires package hddtemp and smartctl!

echo ""
hostnamectl
echo "            Uptime: `uptime --pretty` since `uptime --since`"
echo "   HDD Temperature: `hddtemp --unit=C /dev/sda`" 
echo ""
free -h

echo "\n+++ Checking S.M.A.R.T. +++"
smartctl --smart=on --nocheck=standby --offlineauto=on --health /dev/sda

echo "\n+++ Checking Filesystem +++"
zpool list
zpool status

echo "\n+++ Checking Updates +++"
apt update && apt upgrade && apt autoremove && snap refresh

echo "\n+++ Cleaning Swap Space +++"
swapoff --all && swapon --all
