<#
.SYNOPSIS
        Writes a generated story
.DESCRIPTION
        This PowerShell script writes a story generated by rules and randomness to the console output.
.EXAMPLE
        PS> ./write-generated-story.ps1
	The angry Ron hits the road.
	...
.LINK
        https://github.com/fleschutz/PowerShell
.NOTES
        Author: Markus Fleschutz | License: CC0
#>

function GetAdverb {
	return "angry","clever","colorful","cool","funny","glad","happy","hot","late","lazy","loud","lovely","nice","poor","rich","romantic","selfish","shy","silent","slow","smart","violent" | Get-Random
}

function GetSubject {
	return "airport","Amy","baby","Ben","Bob","brothers","car","cat","Dick","dog","earth","Eva","fox","guy","jet","Joe","Jon","kids","Leo","Max","man","moon","movies","parents","people","Peter","plane","Pope","Ron","Sam","sisters","sun","Tim","Tom","woman" | Get-Random
}

function GetVerb {
	return "beats","broadcasts","catches","goes to","hits","listens to","loves","talks to","walks to","welcomes" | Get-Random
}

function GetObject {
	return "a ball","a house","a sheep","a table","a vase","god","the church","the road","the tea","the woods","Lisa","Mary" | Get-Random
}

function GetSentence {
	return "The $(GetAdverb) $(GetSubject) $(GetVerb) $(GetObject)."
}


""
"		  A Funny Story"
"		  -------------"
""
"     Generated by a script with rules & randomness."
""
while ($true) { & "$PSScriptRoot/write-typewriter.ps1" $(GetSentence) 20 }
