
""
"              _-o#&&*''''?d:>b\_"
"          _o/'`''  '',, dMF9MMMMMHo_"
"       .o&#'        `'MbHMMMMMMMMMMMHo."
"     .o'' '         vodM*$&&HMMMMMMMMMM?."
"    ,'              $M&ood,~'`(&##MMMMMMH\"
"   /               ,MMMMMMM#b?#bobMMMMHMMML"
"  &              ?MMMMMMMMMMMMMMMMM7MMM$R*Hk"
" ?$.            :MMMMMMMMMMMMMMMMMMM/HMMM|`*L"
"|               |MMMMMMMMMMMMMMMMMMMMbMH'   T,"
"$H#:            `*MMMMMMMMMMMMMMMMMMMMb#}'  `?"
"]MMH#             ''*''''*#MMMMMMMMMMMMM'    -"
"MMMMMb_                   |MMMMMMMMMMMP'     :"
"HMMMMMMMHo                 `MMMMMMMMMT       ."
"?MMMMMMMMP                  9MMMMMMMM}       -"
"-?MMMMMMM                  |MMMMMMMMM?,d-    '"
" :|MMMMMM-                 `MMMMMMMT .M|.   :"
"  .9MMM[                    &MMMMM*' `'    ."
"   :9MMk                    `MMM#'        -"
"     &M}                     '          .-"
"      `&.                             ."
"        `~,   .                     ./"
"            . _                  .-"
"              '`--._,dd###pp='''"
""
exit 0 # success